config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "goals#home"
  resources :goals
  resources :categories
  end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :goals
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/models/profiles.rb
class Profile < ActiveRecord::Base
  has_many :goals
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

#show
  def show
    @category = Category.find(params[:id])
  end
  private
    def category_params
      params.require(:category).permit(:name)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  #index
  def index
    @goals = Goal.all
  end

#show
  def show
    @goal = Goal.find(params[:id])
  end

#new
  def new
    if !user_signed_in?
      flash[:alert] = "You must be signed in to set your goals."
      redirect_to new_user_session_path
    else
        @goal = Goal.new
    end
  end

#create
  def create
    # Goal.create(goal_params.merge(user: current_user))
    @goal = Goal.create!(goal_params)
    redirect_to goal_path(@goal)
  end
  # edit
  def edit
    @goal = Goal.find(params[:id])
  end


  # update
  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)

    redirect_to goal_path(@goal)
  end

  #delete
  def destroy
    if !user_signed_in?
      flash[:alert] = "Only the owner of the goal can delete"
      redirect_to goals_path
    else
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_path
    end
  end

  private
    def goal_params
      params.require(:goal).permit(:name, :age, :photo_url, :title, :description, :deadline, :step1, :step2, :step3, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1> Categories </h1>

<p> Be sure to consider various parts of your life. Focusing only on professional goals could result in missing out on opportunities to enjoy your life. On the other hand, only considering goals about your personal life could result in you not feeling satisfied at work and with your financial situation.</p>

<p> Remember, it is normal to prioritize a certain goal at any given time. Over the course of your life it is important to find the right balance for you.</p>

<h3> The categories and areas of focus we suggest are:<h3>
  <% @categories.each do |category| %>
  <table>
    <tr class="category"><%=  category.name %>
    </tr>
  </table>  
  <% end %>

app/views/goals/edit.html.erb
<%= form_for @goal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age, in: 1.0..100.0 %>

  <%= f.label :date %>
  <%= select_date Date.today, prefix: :creationdate %>

  <%= f.label :photo_URL %>
  <%= f.file_field :photo_url %>

  <%= f.submit %>
<% end %>

app/views/goals/home.html.erb
  <h1>Welcome to the GOALdiggers</h1>

  <div class="what">
    <h3>What is GOALdigger?</h3>
      <p>The importance of setting goals, blah blah blah</p>
  </div>

  <div class ="why">
    <h3>Why should I set goals?</h3>
      <p>The first step in achieving your goals is setting them</p>
  </div>

  <div class ="how">
    <h3>What is the process of setting goals</h3>
      <p> An easy way to break goals down is by timeline and category. It's best to work backwards, starting from 10 or 5 years from now. That way the goals you set for 1 year from now are in line with helping you achieve your longer term goals. It is easy to lose sight of your goals if you only set long-term ones. On the other hand, if you only create goals for the next week or month it is easy to let those slip after you achieve them. By setting both you have a big picture goal that inspires you as well as attainable milestone-goals that motivate you each step of the way. <p>
      <div class="goal-steps">
        <h4>Tips to crushing your goals</h4>
          <ul class='tips'>
            <li>Make sure your goals are simple and clear.</li>
            <li>Make sure your goals are quantifiable and something you can clearly measure.</li>
            <li>Your goals should be achievable yet challenging. </li>
            <li>Share your goals with others to help keep you accountable!</li>
            <li>Do not be discouraged if you do not reach your goals. They are goals because they are challenging. Re-evaluate and re-adjust your goals with new, actionable step and a new timeline. Stay motivated!</li>
            <li>HAVE FUN! There are no right or wrong goals. Your goals are yours and should help exprress who you are, what you value and what you want to work towards in your life.</li>
          </ul>
      </div>
  </div>

app/views/goals/index.html.erb
<div class="container-fluid">
  <h3><%=link_to "Create An Account", new_user_registration_path %></h3>
  <h3> <%=link_to "I want to create my goals!", new_goal_path %></h3>
  <h1>Get to know some GOALdiggers</h1>
  <div class="row">
        <% @goals.each do |goal| %>
        <col>
        <div class="col-sm-3 col-md-4" style="background-color:yellow;">
          <h3>
            <%= link_to goal.name, goal %>
          </h3>
          <h4>
          <%= goal.title %>
        </h4>
        <%= goal.category.name %>
      </col>
    </div>
        <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<h2>I'm a GOALdigger</h2>

<%= form_for @goal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age, in: 1.0..100.0 %>

  <%= f.label :date %>
  <%= select_date Date.today, prefix: :creationdate %>

  <%= f.label :photo_URL %>
  <%= f.file_field :photo_url %>

  <%= f.label :Category %>
  <%= f.select :category, [['Fun','fun'],['Personal','personal'],['Career','career'],['Financial', 'financial'], ['Health','health']] %>
  <%= f.submit %>
<% end %>

app/views/goals/show.html.erb
<h1><%= @goal.name %></h1>
<%= @goal.photo_url%>
<div class = 'link'>
<%= link_to "Edit Goal", edit_goal_path %>
<%= link_to "Delete Goal", goal_path, method: :delete %>
</div>

<button><%= link_to "I'm Ready To Set My Goals!", new_goal_path  %><button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOALdigger</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <%= javascript_include_tag :defaults %> -->
  <%= csrf_meta_tags %>


</head>
<body>
  <nav>
    <ul id="top-left-nav-bar">
      <li> <%=link_to "home", root_path %> </li>
      <li>  <%=link_to "goalers", goals_path %></li>
      <li> <%= link_to "categories", categories_path %> </li>
      <!-- <li> contact<a href="#">contact</a></li> -->
    </ul>
    <ul id="top-right-nav-bar">
        <li>
          <%= link_to "sign-up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'sign-in', new_user_session_path %>
        </li>
        <% if user_signed_in?  %>
        <li>
          <%= link_to 'sign-out', destroy_user_session_path, :method => :delete %>
        </li>
        <% end %>
      </ul>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="content">

<%= yield %>

</div>
</body>
</html>